import 'package:freezed_annotation/freezed_annotation.dart';

part 'clinical_insight.freezed.dart';

/// Clinical insight generated by correlation engine
@freezed
abstract class ClinicalInsight with _$ClinicalInsight {
  const factory ClinicalInsight({
    required String id,
    required InsightType type,
    required InsightSeverity severity,
    required String title,
    required String description,
    required List<String> evidencePoints,
    required DateTime detectedAt,
    String? recommendation,
    List<String>? affectedVitals,
    List<String>? relatedMedications,
    double? confidenceScore, // 0-1
    bool? acknowledged,
  }) = _ClinicalInsight;

  const ClinicalInsight._();

  /// Get severity color
  String get severityColor {
    switch (severity) {
      case InsightSeverity.critical:
        return 'critical';
      case InsightSeverity.warning:
        return 'warning';
      case InsightSeverity.info:
        return 'info';
    }
  }

  /// Get type icon
  String get typeIcon {
    switch (type) {
      case InsightType.correlation:
        return 'link';
      case InsightType.trend:
        return 'trending_up';
      case InsightType.deviation:
        return 'show_chart';
      case InsightType.prediction:
        return 'psychology';
      case InsightType.medication:
        return 'medication';
      case InsightType.activity:
        return 'directions_walk';
    }
  }
}

/// Types of clinical insights
enum InsightType {
  correlation, // Correlation between events
  trend, // Trend analysis
  deviation, // Baseline deviation
  prediction, // Risk prediction
  medication, // Medication-related
  activity, // Activity-related
}

/// Insight severity levels
enum InsightSeverity {
  critical, // Requires immediate attention
  warning, // Needs review
  info, // Informational
}

/// Correlation between two events/vitals
@freezed
abstract class ClinicalCorrelation with _$ClinicalCorrelation {
  const factory ClinicalCorrelation({
    required String event1,
    required String event2,
    required DateTime timestamp1,
    required DateTime timestamp2,
    required String correlationType, // 'causal', 'temporal', 'pattern'
    required double strength, // 0-1
    String? explanation,
  }) = _ClinicalCorrelation;

  const ClinicalCorrelation._();

  /// Get time difference between events
  Duration get timeDifference {
    return timestamp2.difference(timestamp1).abs();
  }

  /// Get correlation strength label
  String get strengthLabel {
    if (strength >= 0.8) return 'Strong';
    if (strength >= 0.5) return 'Moderate';
    return 'Weak';
  }
}

/// Risk prediction model
@freezed
abstract class RiskPrediction with _$RiskPrediction {
  const factory RiskPrediction({
    required RiskType riskType,
    required double probability, // 0-1
    required List<String> contributingFactors,
    required DateTime predictedTimeframe,
    String? preventionRecommendation,
  }) = _RiskPrediction;

  const RiskPrediction._();

  /// Get risk level
  String get riskLevel {
    if (probability >= 0.7) return 'High';
    if (probability >= 0.4) return 'Moderate';
    return 'Low';
  }
}

/// Types of risks
enum RiskType {
  fall,
  infection,
  dehydration,
  medication_adverse,
  hospitalization,
  deterioration,
}
